# Generated by Django 2.0.2 on 2018-02-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price_value', models.IntegerField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_number', models.IntegerField(max_length=100)),
                ('is_checked_out', models.BooleanField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AudioVideo',
            fields=[
                ('document_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='documents.Document')),
            ],
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('document_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='documents.Document')),
                ('is_best_seller', models.BooleanField(max_length=10)),
                ('edition', models.IntegerField(max_length=100)),
            ],
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='JournalArticles',
            fields=[
                ('document_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='documents.Document')),
            ],
            bases=('documents.document',),
        ),
        migrations.AddField(
            model_name='copy',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='copies',
                                    to='documents.Document'),
        ),
        migrations.AddField(
            model_name='copy',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_card',
                                    to='library.UserCard'),
        ),
    ]
